BucHunt/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BucHunt.Controllers;
using BucHunt.Models;
using DataLibrary.DBLogic;

namespace BucHunt.Controllers
{
    public class HomeController : Controller
    {
        EmailProcess email = new EmailProcess();
        CodeProcessor code = new CodeProcessor();
        string AccessCode;

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }

        public ActionResult SignUp()
        {
            ViewBag.Title = "Sign Up";

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(ParticipantModel participant)
        {
            if(ModelState.IsValid)
            {
                //Sends Access Code to the participants through email and text
                AccessCode = code.CreateAccessCode();
                email.SendEmail(participant.Email, AccessCode);
                if(email.SendTexts(participant.PhoneNumber, participant.provider, AccessCode))
                {
                    ViewBag.Title = "Successful Sign Up";
                    return RedirectToAction("SuccessfulSignUp", "Home", new { AccessCode });
                }
                else //Sends message if the text does not successfully send
                {
                    ViewBag.Error = "Text Message Did Not Send.\nTry Again";
                }
            }
            

            return View();
        }
        public ActionResult SuccessfulSignUp(string accesscode)
        {
            ViewBag.Title = "Successful Sign Up";
            ViewBag.AccessCode = accesscode;
            return View();
        }
        public ActionResult dummySignUp()
        {
            ViewBag.Title = "Dummy Sign Up";

            return View();
        }
    }
}

BucHunt/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BucHunt.Models;
using DataLibrary.DBLogic;

namespace BucHunt.Controllers
{
    public class LocationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: LocationModels        
        /// <summary>
        /// displays the list of locations.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var data = LocationProcessor.LoadLocations();
            List<LocationModel> locations = new List<LocationModel>();
            foreach (var row in data)
            {
                locations.Add(new LocationModel
                {
                    Id = row.Id,
                    LocationName = row.LocationName,
                    DecodedQR = row.DecodedQR,
                    Completion = row.Completion,
                    UserEntry = row.UserEntry
                });
            }

            return View(locations);
        }
        
        // GET: LocationModels/Details/5        
        /// <summary>
        /// displays details for a location.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            var locId = id ?? default(int);
            var data = LocationProcessor.LoadSingleLocation(locId);
            List<LocationModel> locations = new List<LocationModel>();
            foreach (var row in data)
            {
                locations.Add(new LocationModel
                {
                    Id = row.Id,
                    LocationName = row.LocationName,
                    DecodedQR = row.DecodedQR,
                    Completion = row.Completion,
                    UserEntry = row.UserEntry
                });
            }
            // A zero has to be used as the index here because I could not 
            // get the database to return a single object only a list 
            // with one item
            var locationModel = locations[0];

            return View(locationModel);
        }







        // GET: LocationModels/Create        
        /// <summary>
        /// Creates a new location.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,LocationName,Completion,DecodedQR,UserEntry")] LocationModel locationModel)
        {
            if (ModelState.IsValid)
            {
                LocationProcessor.CreateLocation(locationModel.LocationName, locationModel.Completion,
                                                 locationModel.DecodedQR, locationModel.UserEntry);
                return RedirectToAction("Index");
            }

            return View(locationModel);
        }







        // GET: LocationModels/Edit/5        
        /// <summary>
        /// Edits a location.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var locId = id ?? default(int);
            var data = LocationProcessor.LoadSingleLocation(locId);
            List<LocationModel> locations = new List<LocationModel>();
            foreach (var row in data)
            {
                locations.Add(new LocationModel
                {
                    Id = row.Id,
                    LocationName = row.LocationName,
                    DecodedQR = row.DecodedQR,
                    Completion = row.Completion,
                    UserEntry = row.UserEntry
                });
            }
            var locationModel = locations[0];

            if (locationModel == null)
            {
                return HttpNotFound();
            }
            return View(locationModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LocationName,Completion,DecodedQR,UserEntry")] LocationModel locationModel)
        {
            if (ModelState.IsValid)
            {
                LocationProcessor.UpdateLocation(locationModel.Id, locationModel.LocationName, locationModel.Completion,
                                                 locationModel.DecodedQR, locationModel.UserEntry);
                return RedirectToAction("Index");
            }

            return View(locationModel);
        }






        // GET: LocationModels/Delete/5        
        /// <summary>
        /// Deletes a location.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var locId = id ?? default(int);
            var data = LocationProcessor.LoadSingleLocation(locId);
            List<LocationModel> locations = new List<LocationModel>();
            foreach (var row in data)
            {
                locations.Add(new LocationModel
                {
                    Id = row.Id,
                    LocationName = row.LocationName,
                    DecodedQR = row.DecodedQR,
                    Completion = row.Completion,
                    UserEntry = row.UserEntry
                });
            }
            // A zero has to be used as the index here because I could not 
            // get the database to return a single object only a list 
            // with one item
            var locationModel = locations[0];

            if (locationModel == null)
            {
                return HttpNotFound();
            }
            return View(locationModel);
        }

        // POST: LocationModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            LocationProcessor.DeleteLocation(id);
            return RedirectToAction("Index");
        }

        











                
        /// <summary>
        /// checks if user QR code matches stored value.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult QRCodeEntry(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var locId = id ?? default(int);
            var data = LocationProcessor.LoadSingleLocation(locId);
            List<LocationModel> locations = new List<LocationModel>();
            foreach (var row in data)
            {
                locations.Add(new LocationModel
                {
                    Id = row.Id,
                    LocationName = row.LocationName,
                    DecodedQR = row.DecodedQR,
                    Completion = row.Completion,
                    UserEntry = row.UserEntry
                });
            }
            // A zero has to be used as the index here because I could not 
            // get the database to return a single object only a list 
            // with one item
            var locationModel = locations[0];

            if (locationModel == null)
            {
                return HttpNotFound();
            }
            return View(locationModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult QRCodeEntry([Bind(Include = "Id,LocationName,Completion,DecodedQR,UserEntry")] LocationModel locationModel)
        {
            LocationModel location = new LocationModel()
            {
                Id = locationModel.Id,
                LocationName = locationModel.LocationName,
                Completion = locationModel.Completion,
                DecodedQR = locationModel.DecodedQR,
                UserEntry = locationModel.UserEntry
            };

            if (ModelState.IsValid)
            {
                if (location.DecodedQR == location.UserEntry)
                {
                    location.Completion = "Complete";
                }
                else
                {
                    location.Completion = "Incomplete";
                }
                LocationProcessor.UpdateLocation(location.Id, location.LocationName, location.Completion,
                                                 location.DecodedQR, location.UserEntry);
                return RedirectToAction("Index");
            }
            return View(location);
        }





        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BucHunt/Views/Home/Index.cshtml
<style>
    body {
        background-color: #041E42;
    }

    h1 {
        font-weight: 600;
        color: #ffc72c
    }

    h3 {
        font-weight: 300;
        color: #ffc72c
    }

    label {
        color: white
    }
</style>
<center>
    <h1>
        WELCOME TO BUCHUNT
    </h1>
</center>
<center>
    <div class="col-8 card">
    </div>
        <div class="col-12 row">
            <p>&nbsp;</p>
        </div>
        <div class="col-12 row">
            <img src="~/Images/logo.png" width="250" height="200" />
        </div>
        <div class="col">
            <center>
                <h3>User Login</h3>
            </center>
        </div>
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <div class="row">
        </div>
            <div class="col">
            </div>
                <label>User ID</label>
                <div class="form-group">
                    <input class="form-control" ID="TextBox1" placeholder="User ID" name="User ID">
                </div>
                <label>Password</label>
                <div class="form-group">
                    <input class="form-control" ID="Password" placeholder="Password" name="Password" type="Password">
                </div>
                <div class="form-group">
                    <input class="btn btn-success btn-block btn-md" onclick="location.href='@Url.Action("Index", "Locations")'" id="Button2" type="button" value="Log In" />
                </div>
                </center>
                <center>
                <div class="form-group">
                    <input class="btn btn-info btn-block btn-md" onclick="location.href='@Url.Action("SignUp", "Home")'" id="Button2" type="button" value="Sign Up" />
                </div>
                </center>
           

BucHunt/Views/Home/SignUp.cshtml
@using BucHunt.Models
@model BucHunt.Models.ParticipantModel
<style>
    body {
        background-color: #041E42;
    }

    h1 {
        font-weight: 600;
        color: #ffc72c
    }

    h3 {
        font-weight: 300;
        color: #ffc72c
    }

    label {
        color: white
    }
</style>
<center>
    <h1>
        WELCOME TO BUCHUNT
    </h1>
</center>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <center>
        <div class="col-8 card">
            <div class="col-12 row">
                <p>&nbsp;</p>
            </div>
            <div class="col-12 row">
                <img src="~/Images/logo.png" width="250" height="200" />
            </div>
            <div class="col">
                <center>
                    <h3>User Sign Up</h3>
                </center>
            </div>
            <div class="row">
                <div class="col">
                    <hr>
                </div>
            </div>
            <div class="row">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col">
                    <label>Email Address</label>
                    <div class="form-group">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email Address" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                    <label>Phone Number</label>
                    <div class="form-group">
                        <div>
                            @Html.DropDownListFor(model => model.provider,
                                                        new SelectList(Enum.GetValues(typeof(Providers))),
                                                        "Select Provider", new { htmlAttributes = new { @class = "form-control" } })
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "Phone Number" } })
                        </div>

                    </div>
                    <div class="form-group">
                        <div>
                            @Html.ValidationMessageFor(model => model.provider, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="text-danger">
                        @ViewBag.Error
                    </div>
                    <center>
                        <div class="form-group">
                            <input class="btn btn-info btn-block btn-lg" id="Button2" type="submit" value="Submit" />
                        </div>
                    </center>
                </div>
            </div>
        </div>
        <div class="col-12 row">
            <p>&nbsp;</p>
        </div>
    </center>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


BucHunt/Views/Home/SuccessfulSignUp.cshtml
<style>
    body {
        background-color: #041E42;
    }

    h1 {
        font-weight: 600;
        color: #ffc72c
    }

    h2 {
        font-weight: 900;
        color: #ffc72c
    }

    h3 {
        font-weight: 300;
        color: #ffc72c
    }

    label {
        color: white
    }
</style>
<center>
    <h1>
        WELCOME TO BUCHUNT
    </h1>
</center>
<center>
    <div class="col-8 card">
        <div class="col-12 row">
            <p>&nbsp;</p>
        </div>
        <div class="col-12 row">
            <img src="~/Images/logo.png" width="250" height="200" />
        </div>
        <div class="col">
            <center>
                <h3>Your sign up was a success!</h3>
                <hr>
            </center>
        </div>
        <div class="col">
            <center>
                <h2>Your User ID: @ViewBag.AccessCode</h2>
                <br />
            </center>
        </div>
        <div class="form-group">
            <input class="btn btn-success btn-block btn-lg" onclick="location.href='@Url.Action("Index", "Home")'" id="Button2" type="button" value="Return to Log In" />
        </div>
        <div class="col-12 row">
            <p>&nbsp;</p>
        </div>
    </div>
</center>

BucHunt/Views/Home/dummySignUp.cshtml
@model BucHunt.Models.ParticipantModel

@{
    ViewBag.Title = "dummySignUp";
}

<h2>dummySignUp</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ParticipantModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.AccessCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AccessCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AccessCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RetypePassWd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RetypePassWd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RetypePassWd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}